export const CONFIG = {
  API_URL: 'http://localhost:5001/api',
  MIN_ANSWER_LENGTH: 10,
  MIN_ANSWER_WORDS: 3,
  MIN_QUESTION_LENGTH: 20,
  MIN_QUESTION_WORDS: 5,
  MIN_TEXT_LENGTH: 20,
  MIN_WORDS: 5,
  CACHE_TTL: 1000 * 60 * 5, // 5 minutes
};